### ISSUE TITLE
Gmapcatcher Error

### ISSUE THREAD

**Issue by tonysmartantzoulatos** [yaapu/FrskyTelemetryScript#194]
Just installed gmapcatcher on win10pro and i am receiving the following error on the maps log.
Traceback (most recent call last):
  File "maps.py", line 15, in <module>
  File "gmapcatcher\mapGPS.pyc", line 11, in <module>
  File "gmapcatcher\mapConst.pyc", line 160, in <module>
LookupError: unknown encoding: cp65001

**Comment by yaapu** [comment]
this is stale, I'm closing it, please reopenif needed
